const PORT = process.env.PORT || 5000;
const MONGODB_URI = process.env.MONGODB_URI;

const SALESFORCE_CLIENT_ID = process.env.SALESFORCE_CLIENT_ID;
const SALESFORCE_CLIENT_SECRET = process.env.SALESFORCE_CLIENT_SECRET;
const SALESFORCE_REDIRECT_URI = process.env.SALESFORCE_REDIRECT_URI;

const SHAREPOINT_CLIENT_ID = process.env.SHAREPOINT_CLIENT_ID;
const SHAREPOINT_CLIENT_SECRET = process.env.SHAREPOINT_CLIENT_SECRET;
const SHAREPOINT_REDIRECT_URI = process.env.SHAREPOINT_REDIRECT_URI;
const SHAREPOINT_TENANT_ID = process.env.SHAREPOINT_TENANT_ID;


module.exports = {
  PORT,
  MONGODB_URI,
  SALESFORCE_CLIENT_ID,
  SALESFORCE_CLIENT_SECRET,
  SALESFORCE_REDIRECT_URI,
  SHAREPOINT_CLIENT_ID,
  SHAREPOINT_CLIENT_SECRET,
  SHAREPOINT_REDIRECT_URI,
  SHAREPOINT_TENANT_ID
};